// EMPLOYEE CONTEXT
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";
export const CLEAR_EMPLOYEES = "CLEAR_EMPLOYEES";
export const CLEAR_FILTER = "CLEAR_FILTER";
 
export const SET_FILL_CURRENT = "SET_FILL_CURRENT";
export const CLEAR_FILL_CURRENT = "CLEAR_FILL_CURRENT";
export const FORM_ERROR = "FORM_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// APP CONTEXT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

 